name: OpenAPI CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  security-scan:
    name: Security Scan with 42Crunch
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: 42Crunch API Security Audit
      uses: 42Crunch/api-security-audit-action@v3
      with:
        api-token: ${{ secrets.API_TOKEN_42CRUNCH }}
        platform-url: https://platform.42crunch.com
        default-collection-name: UKGDS-APIs
        upload-to-code-scanning: true
        log-level: info
        sarif-report: 42c-audit-report.sarif
        
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: 42c-audit-report.sarif
        category: 42crunch-api-security
